modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Bed-Benefits/issues"
license="LGPL v2.1"

[[mods]]
modId="bedbenefits"
updateJSONURL="https://updates.blamejared.com/get?n=bedbenefits&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.bedbenefits]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="SERVER"

[[dependencies.bedbenefits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="SERVER"
    
[[dependencies.bedbenefits]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="AFTER"
    side="SERVER"