modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Bed-Benefits/issues"

[[mods]]
modId="bedbenefits"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.bedbenefits]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.bedbenefits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="SERVER"
    
[[dependencies.bedbenefits]]
    modId="bookshelf"
    mandatory=true
    versionRange="[5.4.13,)"
    ordering="AFTER"
    side="BOTH"